version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: volatco_shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: volatco
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
  wordpress:
    image: wordpress:latest
    container_name: volatco_shop
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: volatco
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_network
volumes:
  db_data:
  wp_data:
networks:
  wp_network: